/*!
 * ${copyright}
 */
sap.ui.define([
	"sap/ui/dom/includeStylesheet",
	"sap/ui/core/library",
	"kickstand-ui/dist/kickstand-ui/kickstand-ui"
], function (includeStylesheet) {
	"use strict";

	// stylesheet with CSS properties/variables
	includeStylesheet(sap.ui.require.toUrl("kickstand-ui/dist/kickstand-ui/kickstand-ui.css"));

	// delegate further initialization of this library to the Core
	// Hint: sap.ui.getCore() must still be used to support preload with sync bootstrap!
	sap.ui.getCore().initLibrary({
		name: "kickstand-ui.components",
		version: "${version}",
		dependencies: [ // keep in sync with the ui5.yaml and .library files
			"sap.ui.core"
		],
		types: [
			//"kickstand-ui.components.ExampleColor"
		],
		interfaces: [],
		controls: [
			"kickstand-ui.components.FormField",
			"kickstand-ui.components.Form",
			"kickstand-ui.components.AccordionSlide",
			"kickstand-ui.components.Accordion",
			"kickstand-ui.components.Alert",
			"kickstand-ui.components.Badge",
			"kickstand-ui.components.Breadcrumbs",
			"kickstand-ui.components.Button",
			"kickstand-ui.components.ButtonBar",
			"kickstand-ui.components.CardBody",
			"kickstand-ui.components.CardFooter",
			"kickstand-ui.components.Card",
			"kickstand-ui.components.CarouselSlide",
			"kickstand-ui.components.Carousel",
			"kickstand-ui.components.DropdownItem",
			"kickstand-ui.components.Dropdown",
			"kickstand-ui.components.Autocomplete",
			"kickstand-ui.components.Checkbox",
			"kickstand-ui.components.Checklist",
			"kickstand-ui.components.Radio",
			"kickstand-ui.components.SpinBox",
			"kickstand-ui.components.Gallery",
			"kickstand-ui.components.Column",
			"kickstand-ui.components.Row",
			"kickstand-ui.components.Icon",
			"kickstand-ui.components.Img",
			"kickstand-ui.components.LoadingOverlay",
			"kickstand-ui.components.Loading",
			"kickstand-ui.components.MenuBar",
			"kickstand-ui.components.MenuGroup",
			"kickstand-ui.components.MenuItem",
			"kickstand-ui.components.MenuRow",
			"kickstand-ui.components.ModalFooter",
			"kickstand-ui.components.Modal",
			"kickstand-ui.components.Overlay",
			"kickstand-ui.components.ProgressBar",
			"kickstand-ui.components.ResponsiveEmbed",
			"kickstand-ui.components.ScrollToTop",
			"kickstand-ui.components.SideDrawer",
			"kickstand-ui.components.Switch",
			"kickstand-ui.components.Tab",
			"kickstand-ui.components.Tabs",
			"kickstand-ui.components.Tooltip",
		],
		elements: [],
		noLibraryCSS: true
	});

	/**
	 * Some description about <code>kickstand-ui.components</code>
	 *
	 * @namespace
	 * @name kickstand-ui.components
	 * @author Generated by Peter Muessig
	 * @version ${version}
	 * @public
	 */
	var thisLib = window["kickstand-ui"]["components"];

	/**
	 * Semantic Colors of the <code>kickstand-ui.components.Example</code>.
	 *
	 * @enum {string}
	 * @public
	 */
	//thisLib.ExampleColor = {
	//
	//	/**
	//	 * Default color (brand color)
	//	 * @public
	//	 */
	//	Default : "Default",
	//
	//	/**
	//	 * Highlight color
	//	 * @public
	//	 */
	//	Highlight : "Highlight"
	//
	//};

	return thisLib;

});
